// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: circles.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one

INSERT INTO circle_members (circle_id, user_id, role, precision_mode)
VALUES ($1, $2, $3, 'precise')
ON CONFLICT (circle_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING circle_id, user_id, role, precision_mode, joined_at, profile_enc
`

type AddMemberParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

// --- membership ---
func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.CircleID, arg.UserID, arg.Role)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.PrecisionMode,
		&i.JoinedAt,
		&i.ProfileEnc,
	)
	return i, err
}

const allCircleRetention = `-- name: AllCircleRetention :many
SELECT id, retention_days FROM circles
`

type AllCircleRetentionRow struct {
	ID            uuid.UUID
	RetentionDays int32
}

func (q *Queries) AllCircleRetention(ctx context.Context) ([]AllCircleRetentionRow, error) {
	rows, err := q.db.Query(ctx, allCircleRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllCircleRetentionRow{}
	for rows.Next() {
		var i AllCircleRetentionRow
		if err := rows.Scan(&i.ID, &i.RetentionDays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpCircleKeyEpoch = `-- name: BumpCircleKeyEpoch :one
UPDATE circles SET key_epoch = key_epoch + 1 WHERE id = $1 RETURNING id, name_enc, retention_days, key_epoch, created_by, created_at
`

func (q *Queries) BumpCircleKeyEpoch(ctx context.Context, id uuid.UUID) (Circle, error) {
	row := q.db.QueryRow(ctx, bumpCircleKeyEpoch, id)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.RetentionDays,
		&i.KeyEpoch,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM circle_members WHERE circle_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, circleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCircle = `-- name: CreateCircle :one
INSERT INTO circles (name_enc, retention_days, created_by)
VALUES ($1, $2, $3)
RETURNING id, name_enc, retention_days, key_epoch, created_by, created_at
`

type CreateCircleParams struct {
	NameEnc       []byte
	RetentionDays int32
	CreatedBy     uuid.UUID
}

func (q *Queries) CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error) {
	row := q.db.QueryRow(ctx, createCircle, arg.NameEnc, arg.RetentionDays, arg.CreatedBy)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.RetentionDays,
		&i.KeyEpoch,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCircle = `-- name: DeleteCircle :exec
DELETE FROM circles WHERE id = $1
`

func (q *Queries) DeleteCircle(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCircle, id)
	return err
}

const getCircle = `-- name: GetCircle :one
SELECT id, name_enc, retention_days, key_epoch, created_by, created_at FROM circles WHERE id = $1
`

func (q *Queries) GetCircle(ctx context.Context, id uuid.UUID) (Circle, error) {
	row := q.db.QueryRow(ctx, getCircle, id)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.RetentionDays,
		&i.KeyEpoch,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT circle_id, user_id, role, precision_mode, joined_at, profile_enc FROM circle_members WHERE circle_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.CircleID, arg.UserID)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.PrecisionMode,
		&i.JoinedAt,
		&i.ProfileEnc,
	)
	return i, err
}

const listCirclesForUser = `-- name: ListCirclesForUser :many
SELECT c.id, c.name_enc, c.retention_days, c.key_epoch, c.created_by, c.created_at, cm.role, cm.precision_mode
FROM circles c
JOIN circle_members cm ON cm.circle_id = c.id
WHERE cm.user_id = $1
ORDER BY c.created_at
`

type ListCirclesForUserRow struct {
	ID            uuid.UUID
	NameEnc       []byte
	RetentionDays int32
	KeyEpoch      int32
	CreatedBy     uuid.UUID
	CreatedAt     time.Time
	Role          string
	PrecisionMode string
}

func (q *Queries) ListCirclesForUser(ctx context.Context, userID uuid.UUID) ([]ListCirclesForUserRow, error) {
	rows, err := q.db.Query(ctx, listCirclesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCirclesForUserRow{}
	for rows.Next() {
		var i ListCirclesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.NameEnc,
			&i.RetentionDays,
			&i.KeyEpoch,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
			&i.PrecisionMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT cm.circle_id, cm.user_id, cm.role, cm.precision_mode, cm.joined_at, cm.profile_enc, u.email
FROM circle_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.circle_id = $1
ORDER BY cm.joined_at
`

type ListMembersRow struct {
	CircleID      uuid.UUID
	UserID        uuid.UUID
	Role          string
	PrecisionMode string
	JoinedAt      time.Time
	ProfileEnc    []byte
	Email         string
}

func (q *Queries) ListMembers(ctx context.Context, circleID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.CircleID,
			&i.UserID,
			&i.Role,
			&i.PrecisionMode,
			&i.JoinedAt,
			&i.ProfileEnc,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM circle_members WHERE circle_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.CircleID, arg.UserID)
	return err
}

const setMemberProfile = `-- name: SetMemberProfile :exec
UPDATE circle_members SET profile_enc = $3 WHERE circle_id = $1 AND user_id = $2
`

type SetMemberProfileParams struct {
	CircleID   uuid.UUID
	UserID     uuid.UUID
	ProfileEnc []byte
}

func (q *Queries) SetMemberProfile(ctx context.Context, arg SetMemberProfileParams) error {
	_, err := q.db.Exec(ctx, setMemberProfile, arg.CircleID, arg.UserID, arg.ProfileEnc)
	return err
}

const setMemberRole = `-- name: SetMemberRole :one
UPDATE circle_members SET role = $3
WHERE circle_id = $1 AND user_id = $2
RETURNING circle_id, user_id, role, precision_mode, joined_at, profile_enc
`

type SetMemberRoleParams struct {
	CircleID uuid.UUID
	UserID   uuid.UUID
	Role     string
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, setMemberRole, arg.CircleID, arg.UserID, arg.Role)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.PrecisionMode,
		&i.JoinedAt,
		&i.ProfileEnc,
	)
	return i, err
}

const setPrecisionMode = `-- name: SetPrecisionMode :one
UPDATE circle_members SET precision_mode = $3
WHERE circle_id = $1 AND user_id = $2
RETURNING circle_id, user_id, role, precision_mode, joined_at, profile_enc
`

type SetPrecisionModeParams struct {
	CircleID      uuid.UUID
	UserID        uuid.UUID
	PrecisionMode string
}

func (q *Queries) SetPrecisionMode(ctx context.Context, arg SetPrecisionModeParams) (CircleMember, error) {
	row := q.db.QueryRow(ctx, setPrecisionMode, arg.CircleID, arg.UserID, arg.PrecisionMode)
	var i CircleMember
	err := row.Scan(
		&i.CircleID,
		&i.UserID,
		&i.Role,
		&i.PrecisionMode,
		&i.JoinedAt,
		&i.ProfileEnc,
	)
	return i, err
}

const updateCircleName = `-- name: UpdateCircleName :one
UPDATE circles SET name_enc = $2 WHERE id = $1 RETURNING id, name_enc, retention_days, key_epoch, created_by, created_at
`

type UpdateCircleNameParams struct {
	ID      uuid.UUID
	NameEnc []byte
}

func (q *Queries) UpdateCircleName(ctx context.Context, arg UpdateCircleNameParams) (Circle, error) {
	row := q.db.QueryRow(ctx, updateCircleName, arg.ID, arg.NameEnc)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.RetentionDays,
		&i.KeyEpoch,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateCircleRetention = `-- name: UpdateCircleRetention :one
UPDATE circles SET retention_days = $2 WHERE id = $1 RETURNING id, name_enc, retention_days, key_epoch, created_by, created_at
`

type UpdateCircleRetentionParams struct {
	ID            uuid.UUID
	RetentionDays int32
}

func (q *Queries) UpdateCircleRetention(ctx context.Context, arg UpdateCircleRetentionParams) (Circle, error) {
	row := q.db.QueryRow(ctx, updateCircleRetention, arg.ID, arg.RetentionDays)
	var i Circle
	err := row.Scan(
		&i.ID,
		&i.NameEnc,
		&i.RetentionDays,
		&i.KeyEpoch,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
