// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: devices.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, platform, display_name, pubkey)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, platform, display_name, pubkey, push_token, created_at, last_seen
`

type CreateDeviceParams struct {
	UserID      uuid.UUID
	Platform    string
	DisplayName *string
	Pubkey      []byte
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Platform,
		arg.DisplayName,
		arg.Pubkey,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.DisplayName,
		&i.Pubkey,
		&i.PushToken,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getDevice = `-- name: GetDevice :one
SELECT id, user_id, platform, display_name, pubkey, push_token, created_at, last_seen FROM devices WHERE id = $1
`

func (q *Queries) GetDevice(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.DisplayName,
		&i.Pubkey,
		&i.PushToken,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getDeviceForUser = `-- name: GetDeviceForUser :one
SELECT id, user_id, platform, display_name, pubkey, push_token, created_at, last_seen FROM devices WHERE id = $1 AND user_id = $2
`

type GetDeviceForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDeviceForUser(ctx context.Context, arg GetDeviceForUserParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceForUser, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.DisplayName,
		&i.Pubkey,
		&i.PushToken,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const listCircleDevices = `-- name: ListCircleDevices :many
SELECT d.id, d.user_id, d.platform, d.display_name, d.pubkey, d.push_token, d.created_at, d.last_seen
FROM devices d
JOIN circle_members cm ON cm.user_id = d.user_id
WHERE cm.circle_id = $1
ORDER BY d.created_at
`

// List devices of all members of a circle (recipients for key envelopes).
func (q *Queries) ListCircleDevices(ctx context.Context, circleID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listCircleDevices, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.DisplayName,
			&i.Pubkey,
			&i.PushToken,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesForUser = `-- name: ListDevicesForUser :many
SELECT id, user_id, platform, display_name, pubkey, push_token, created_at, last_seen FROM devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDevicesForUser(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.DisplayName,
			&i.Pubkey,
			&i.PushToken,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDevicePubkey = `-- name: SetDevicePubkey :exec
UPDATE devices SET pubkey = $2 WHERE id = $1
`

type SetDevicePubkeyParams struct {
	ID     uuid.UUID
	Pubkey []byte
}

func (q *Queries) SetDevicePubkey(ctx context.Context, arg SetDevicePubkeyParams) error {
	_, err := q.db.Exec(ctx, setDevicePubkey, arg.ID, arg.Pubkey)
	return err
}

const setDevicePushToken = `-- name: SetDevicePushToken :exec
UPDATE devices SET push_token = $2 WHERE id = $1
`

type SetDevicePushTokenParams struct {
	ID        uuid.UUID
	PushToken *string
}

func (q *Queries) SetDevicePushToken(ctx context.Context, arg SetDevicePushTokenParams) error {
	_, err := q.db.Exec(ctx, setDevicePushToken, arg.ID, arg.PushToken)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE devices SET last_seen = now() WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}
