// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: invites.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeInvite = `-- name: ConsumeInvite :one
UPDATE invites
SET uses = uses + 1
WHERE id = $1
  AND status = 'active'
  AND expires_at > now()
  AND uses < max_uses
RETURNING id, circle_id, created_by, role, max_uses, uses, expires_at, status, created_at
`

// Atomically consume one use of an active, unexpired invite. Returns the row
// only if a use was available (uses < max_uses); NULL otherwise.
func (q *Queries) ConsumeInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, consumeInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CreatedBy,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const countRecentInvitesByUser = `-- name: CountRecentInvitesByUser :one
SELECT count(*) FROM invites
WHERE created_by = $1 AND created_at > now() - interval '1 hour'
`

func (q *Queries) CountRecentInvitesByUser(ctx context.Context, createdBy uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentInvitesByUser, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (circle_id, created_by, role, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, circle_id, created_by, role, max_uses, uses, expires_at, status, created_at
`

type CreateInviteParams struct {
	CircleID  uuid.UUID
	CreatedBy uuid.UUID
	Role      string
	MaxUses   int32
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.CircleID,
		arg.CreatedBy,
		arg.Role,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CreatedBy,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getInvite = `-- name: GetInvite :one
SELECT id, circle_id, created_by, role, max_uses, uses, expires_at, status, created_at FROM invites WHERE id = $1
`

func (q *Queries) GetInvite(ctx context.Context, id uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getInvite, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.CreatedBy,
		&i.Role,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitesForCircle = `-- name: ListInvitesForCircle :many
SELECT id, circle_id, created_by, role, max_uses, uses, expires_at, status, created_at FROM invites
WHERE circle_id = $1 AND status = 'active' AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListInvitesForCircle(ctx context.Context, circleID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listInvitesForCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.CreatedBy,
			&i.Role,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :exec
UPDATE invites SET status = 'revoked' WHERE id = $1 AND circle_id = $2
`

type RevokeInviteParams struct {
	ID       uuid.UUID
	CircleID uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) error {
	_, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.CircleID)
	return err
}
