// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_envelopes.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createKeyEnvelope = `-- name: CreateKeyEnvelope :one
INSERT INTO key_envelopes (
    circle_id, recipient_device_id, sender_device_id, ciphertext, key_epoch
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (circle_id, recipient_device_id, key_epoch) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext,
    sender_device_id = EXCLUDED.sender_device_id,
    created_at = now(),
    consumed_at = NULL
RETURNING id, circle_id, recipient_device_id, sender_device_id, ciphertext, key_epoch, created_at, consumed_at
`

type CreateKeyEnvelopeParams struct {
	CircleID          uuid.UUID
	RecipientDeviceID uuid.UUID
	SenderDeviceID    *uuid.UUID
	Ciphertext        []byte
	KeyEpoch          int32
}

// Upsert one sealed key per (circle, recipient device, epoch): re-sending the
// rotated key replaces the prior envelope and re-arms it for fetching, so the
// table cannot grow without bound from repeated sends.
func (q *Queries) CreateKeyEnvelope(ctx context.Context, arg CreateKeyEnvelopeParams) (KeyEnvelope, error) {
	row := q.db.QueryRow(ctx, createKeyEnvelope,
		arg.CircleID,
		arg.RecipientDeviceID,
		arg.SenderDeviceID,
		arg.Ciphertext,
		arg.KeyEpoch,
	)
	var i KeyEnvelope
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.RecipientDeviceID,
		&i.SenderDeviceID,
		&i.Ciphertext,
		&i.KeyEpoch,
		&i.CreatedAt,
		&i.ConsumedAt,
	)
	return i, err
}

const markEnvelopeConsumed = `-- name: MarkEnvelopeConsumed :exec
UPDATE key_envelopes SET consumed_at = now()
WHERE id = $1 AND recipient_device_id = $2 AND consumed_at IS NULL
`

type MarkEnvelopeConsumedParams struct {
	ID                uuid.UUID
	RecipientDeviceID uuid.UUID
}

func (q *Queries) MarkEnvelopeConsumed(ctx context.Context, arg MarkEnvelopeConsumedParams) error {
	_, err := q.db.Exec(ctx, markEnvelopeConsumed, arg.ID, arg.RecipientDeviceID)
	return err
}

const pendingEnvelopesForDevice = `-- name: PendingEnvelopesForDevice :many
SELECT id, circle_id, recipient_device_id, sender_device_id, ciphertext, key_epoch, created_at, consumed_at FROM key_envelopes
WHERE recipient_device_id = $1 AND consumed_at IS NULL
ORDER BY created_at
LIMIT 500
`

// Pending (unconsumed) envelopes addressed to a device, bounded.
func (q *Queries) PendingEnvelopesForDevice(ctx context.Context, recipientDeviceID uuid.UUID) ([]KeyEnvelope, error) {
	rows, err := q.db.Query(ctx, pendingEnvelopesForDevice, recipientDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyEnvelope{}
	for rows.Next() {
		var i KeyEnvelope
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.RecipientDeviceID,
			&i.SenderDeviceID,
			&i.Ciphertext,
			&i.KeyEpoch,
			&i.CreatedAt,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneKeyEnvelopes = `-- name: PruneKeyEnvelopes :execrows
DELETE FROM key_envelopes
WHERE (consumed_at IS NOT NULL AND consumed_at < now() - interval '7 days')
   OR (consumed_at IS NULL AND created_at < now() - interval '30 days')
`

// Prune consumed envelopes and stale unconsumed ones (privacy + storage bound).
func (q *Queries) PruneKeyEnvelopes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneKeyEnvelopes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
