// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"time"

	"github.com/google/uuid"
)

type AppVersion struct {
	ID           uuid.UUID
	Platform     string
	VersionCode  int32
	VersionName  string
	ApkUrl       *string
	Sha256       *string
	Changelog    *string
	MinSupported int32
	IsActive     bool
	CreatedAt    time.Time
}

type AuditLog struct {
	ID            int64
	Ts            time.Time
	Event         string
	ActorUserID   *uuid.UUID
	ActorDeviceID *uuid.UUID
	CircleID      *uuid.UUID
	Ip            *string
	Detail        []byte
}

type Circle struct {
	ID            uuid.UUID
	NameEnc       []byte
	RetentionDays int32
	KeyEpoch      int32
	CreatedBy     uuid.UUID
	CreatedAt     time.Time
}

type CircleMember struct {
	CircleID      uuid.UUID
	UserID        uuid.UUID
	Role          string
	PrecisionMode string
	JoinedAt      time.Time
	ProfileEnc    []byte
}

type Device struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Platform    string
	DisplayName *string
	Pubkey      []byte
	PushToken   *string
	CreatedAt   time.Time
	LastSeen    *time.Time
}

type Invite struct {
	ID        uuid.UUID
	CircleID  uuid.UUID
	CreatedBy uuid.UUID
	Role      string
	MaxUses   int32
	Uses      int32
	ExpiresAt time.Time
	Status    string
	CreatedAt time.Time
}

type KeyEnvelope struct {
	ID                uuid.UUID
	CircleID          uuid.UUID
	RecipientDeviceID uuid.UUID
	SenderDeviceID    *uuid.UUID
	Ciphertext        []byte
	KeyEpoch          int32
	CreatedAt         time.Time
	ConsumedAt        *time.Time
}

type LoginAttempt struct {
	ID        int64
	Email     *string
	Ip        *string
	Success   bool
	CreatedAt time.Time
}

type NotificationMute struct {
	UserID      uuid.UUID
	CircleID    uuid.UUID
	MutedUserID *uuid.UUID
	CreatedAt   time.Time
}

type Ping struct {
	ID         uuid.UUID
	CircleID   uuid.UUID
	DeviceID   uuid.UUID
	ClientID   string
	Nonce      []byte
	Ciphertext []byte
	CapturedAt time.Time
	ReceivedAt time.Time
	ExpiresAt  *time.Time
}

type PlacesEnc struct {
	ID         uuid.UUID
	CircleID   uuid.UUID
	Ciphertext []byte
	Version    int32
	Deleted    bool
	UpdatedBy  *uuid.UUID
	UpdatedAt  time.Time
	CreatedAt  time.Time
	CreatedBy  *uuid.UUID
}

type PushSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DeviceID  *uuid.UUID
	Endpoint  string
	P256dh    *string
	Auth      *string
	CreatedAt time.Time
	Kind      string
}

type Session struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         uuid.UUID
	AccessTokenHash  string
	RefreshTokenHash string
	PrevRefreshHash  *string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	RotatedAt        time.Time
}

type SharePosition struct {
	SessionID  uuid.UUID
	Nonce      []byte
	Ciphertext []byte
	CapturedAt time.Time
	UpdatedAt  time.Time
}

type ShareSession struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	CreatedAt       time.Time
	ExpiresAt       time.Time
	RevokedAt       *time.Time
	ViewerTokenHash []byte
	ViewerBoundAt   *time.Time
}

type SosEvent struct {
	ID         uuid.UUID
	CircleID   uuid.UUID
	DeviceID   *uuid.UUID
	Ciphertext []byte
	CreatedAt  time.Time
	ResolvedAt *time.Time
	ResolvedBy *uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Email     string
	PassHash  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
