// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: mutes.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countMembersIn = `-- name: CountMembersIn :one
SELECT count(*) FROM circle_members
WHERE circle_id = $1 AND user_id = ANY($2::uuid[])
`

type CountMembersInParams struct {
	CircleID uuid.UUID
	UserIds  []uuid.UUID
}

// How many of the given user ids actually belong to the circle. Lets PUT /mutes
// validate a whole mute set in one round trip (count < len → someone is not a
// member) without leaking WHICH id was rejected.
func (q *Queries) CountMembersIn(ctx context.Context, arg CountMembersInParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersIn, arg.CircleID, arg.UserIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMutes = `-- name: DeleteMutes :exec
DELETE FROM notification_mutes WHERE user_id = $1 AND circle_id = $2
`

type DeleteMutesParams struct {
	UserID   uuid.UUID
	CircleID uuid.UUID
}

func (q *Queries) DeleteMutes(ctx context.Context, arg DeleteMutesParams) error {
	_, err := q.db.Exec(ctx, deleteMutes, arg.UserID, arg.CircleID)
	return err
}

const insertMute = `-- name: InsertMute :exec
INSERT INTO notification_mutes (user_id, circle_id, muted_user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertMuteParams struct {
	UserID      uuid.UUID
	CircleID    uuid.UUID
	MutedUserID *uuid.UUID
}

// Idempotent: the UNIQUE (user_id, circle_id, muted_user_id) NULLS NOT DISTINCT
// constraint makes re-muting the same target — or the circle — a no-op.
func (q *Queries) InsertMute(ctx context.Context, arg InsertMuteParams) error {
	_, err := q.db.Exec(ctx, insertMute, arg.UserID, arg.CircleID, arg.MutedUserID)
	return err
}

const listMutes = `-- name: ListMutes :many
SELECT muted_user_id FROM notification_mutes
WHERE user_id = $1 AND circle_id = $2
ORDER BY created_at
`

type ListMutesParams struct {
	UserID   uuid.UUID
	CircleID uuid.UUID
}

// The caller's own mutes in one circle. A NULL muted_user_id row means the
// whole circle is muted; every other row names one muted member.
func (q *Queries) ListMutes(ctx context.Context, arg ListMutesParams) ([]*uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMutes, arg.UserID, arg.CircleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*uuid.UUID{}
	for rows.Next() {
		var muted_user_id *uuid.UUID
		if err := rows.Scan(&muted_user_id); err != nil {
			return nil, err
		}
		items = append(items, muted_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
