// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pings.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPingsForCircle = `-- name: CountPingsForCircle :one
SELECT count(*) FROM pings WHERE circle_id = $1
`

func (q *Queries) CountPingsForCircle(ctx context.Context, circleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPingsForCircle, circleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertPing = `-- name: InsertPing :one
INSERT INTO pings (
    circle_id, device_id, client_id, nonce, ciphertext, captured_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (device_id, client_id, captured_at) DO NOTHING
RETURNING id, circle_id, device_id, client_id, nonce, ciphertext, captured_at, received_at, expires_at
`

type InsertPingParams struct {
	CircleID   uuid.UUID
	DeviceID   uuid.UUID
	ClientID   string
	Nonce      []byte
	Ciphertext []byte
	CapturedAt time.Time
	ExpiresAt  *time.Time
}

// Idempotent insert of one encrypted ping. Retries of the same
// (device_id, client_id, captured_at) are dropped. Returns the row only when a
// NEW ping was inserted, so the handler knows what to fan out over realtime.
func (q *Queries) InsertPing(ctx context.Context, arg InsertPingParams) (Ping, error) {
	row := q.db.QueryRow(ctx, insertPing,
		arg.CircleID,
		arg.DeviceID,
		arg.ClientID,
		arg.Nonce,
		arg.Ciphertext,
		arg.CapturedAt,
		arg.ExpiresAt,
	)
	var i Ping
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.DeviceID,
		&i.ClientID,
		&i.Nonce,
		&i.Ciphertext,
		&i.CapturedAt,
		&i.ReceivedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const latestPingsForCircle = `-- name: LatestPingsForCircle :many
SELECT DISTINCT ON (device_id) id, circle_id, device_id, client_id, nonce, ciphertext, captured_at, received_at, expires_at
FROM pings
WHERE circle_id = $1
ORDER BY device_id, captured_at DESC
`

// Latest ping per device in a circle (for the live map).
func (q *Queries) LatestPingsForCircle(ctx context.Context, circleID uuid.UUID) ([]Ping, error) {
	rows, err := q.db.Query(ctx, latestPingsForCircle, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ping{}
	for rows.Next() {
		var i Ping
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.DeviceID,
			&i.ClientID,
			&i.Nonce,
			&i.Ciphertext,
			&i.CapturedAt,
			&i.ReceivedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
