// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: places.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPlace = `-- name: CreatePlace :one
INSERT INTO places_enc (circle_id, ciphertext, version, created_by, updated_by)
VALUES ($1, $2, 1, $3, $3)
RETURNING id, circle_id, ciphertext, version, deleted, updated_by, updated_at, created_at, created_by
`

type CreatePlaceParams struct {
	CircleID   uuid.UUID
	Ciphertext []byte
	AuthorID   *uuid.UUID
}

// The author is both the creator and (so far) the last editor. created_by is set
// ONLY here: no update path may rewrite it, so "«Home» · <owner nick>" keeps
// naming who added the place, not whoever touched it last.
func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (PlacesEnc, error) {
	row := q.db.QueryRow(ctx, createPlace, arg.CircleID, arg.Ciphertext, arg.AuthorID)
	var i PlacesEnc
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Ciphertext,
		&i.Version,
		&i.Deleted,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listPlaces = `-- name: ListPlaces :many
SELECT id, circle_id, ciphertext, version, deleted, updated_by, updated_at, created_at, created_by FROM places_enc
WHERE circle_id = $1 AND deleted = false
ORDER BY created_at
`

func (q *Queries) ListPlaces(ctx context.Context, circleID uuid.UUID) ([]PlacesEnc, error) {
	rows, err := q.db.Query(ctx, listPlaces, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlacesEnc{}
	for rows.Next() {
		var i PlacesEnc
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.Ciphertext,
			&i.Version,
			&i.Deleted,
			&i.UpdatedBy,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const prunePlaceTombstones = `-- name: PrunePlaceTombstones :execrows
DELETE FROM places_enc
WHERE deleted = true AND updated_at < $1
`

// Hard-delete soft-deleted place tombstones once clients have had time to
// converge the deletion (privacy + storage bound).
func (q *Queries) PrunePlaceTombstones(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, prunePlaceTombstones, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlace = `-- name: SoftDeletePlace :one
UPDATE places_enc
SET deleted = true, version = version + 1, updated_by = $3, updated_at = now()
WHERE id = $1 AND circle_id = $2 AND deleted = false
RETURNING id, circle_id, ciphertext, version, deleted, updated_by, updated_at, created_at, created_by
`

type SoftDeletePlaceParams struct {
	ID        uuid.UUID
	CircleID  uuid.UUID
	UpdatedBy *uuid.UUID
}

// Soft-delete only a live place. The `deleted = false` guard makes re-deleting a
// tombstone a no-op (returns no row → 404) instead of refreshing updated_at
// (which would defeat tombstone retention) or inflating the version.
func (q *Queries) SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) (PlacesEnc, error) {
	row := q.db.QueryRow(ctx, softDeletePlace, arg.ID, arg.CircleID, arg.UpdatedBy)
	var i PlacesEnc
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Ciphertext,
		&i.Version,
		&i.Deleted,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const updatePlace = `-- name: UpdatePlace :one
UPDATE places_enc
SET ciphertext = $3, version = version + 1, updated_by = $4, updated_at = now()
WHERE id = $1 AND circle_id = $2 AND version = $5 AND deleted = false
RETURNING id, circle_id, ciphertext, version, deleted, updated_by, updated_at, created_at, created_by
`

type UpdatePlaceParams struct {
	ID         uuid.UUID
	CircleID   uuid.UUID
	Ciphertext []byte
	UpdatedBy  *uuid.UUID
	Version    int32
}

// Optimistic-concurrency update: only if the caller's version matches.
func (q *Queries) UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (PlacesEnc, error) {
	row := q.db.QueryRow(ctx, updatePlace,
		arg.ID,
		arg.CircleID,
		arg.Ciphertext,
		arg.UpdatedBy,
		arg.Version,
	)
	var i PlacesEnc
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.Ciphertext,
		&i.Version,
		&i.Deleted,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}
