// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	// --- membership ---
	AddMember(ctx context.Context, arg AddMemberParams) (CircleMember, error)
	AllCircleRetention(ctx context.Context) ([]AllCircleRetentionRow, error)
	// One-device binding, compare-and-swap: only the request that finds
	// viewer_token_hash still NULL binds the link and gets the row back. A racing
	// second viewer matches no row and is refused, so a link can never be bound
	// twice.
	BindShareViewer(ctx context.Context, arg BindShareViewerParams) (ShareSession, error)
	BumpCircleKeyEpoch(ctx context.Context, id uuid.UUID) (Circle, error)
	// Atomically consume one use of an active, unexpired invite. Returns the row
	// only if a use was available (uses < max_uses); NULL otherwise.
	ConsumeInvite(ctx context.Context, id uuid.UUID) (Invite, error)
	// How many of the given user ids actually belong to the circle. Lets PUT /mutes
	// validate a whole mute set in one round trip (count < len → someone is not a
	// member) without leaking WHICH id was rejected.
	CountMembersIn(ctx context.Context, arg CountMembersInParams) (int64, error)
	CountOwners(ctx context.Context, circleID uuid.UUID) (int64, error)
	CountPingsForCircle(ctx context.Context, circleID uuid.UUID) (int64, error)
	// Count consecutive recent failures for an email since its last success,
	// within a window. Drives exponential lockout.
	CountRecentFailuresByEmail(ctx context.Context, arg CountRecentFailuresByEmailParams) (int64, error)
	CountRecentFailuresByIP(ctx context.Context, arg CountRecentFailuresByIPParams) (int64, error)
	CountRecentInvitesByUser(ctx context.Context, createdBy uuid.UUID) (int64, error)
	CreateCircle(ctx context.Context, arg CreateCircleParams) (Circle, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	// Upsert one sealed key per (circle, recipient device, epoch): re-sending the
	// rotated key replaces the prior envelope and re-arms it for fetching, so the
	// table cannot grow without bound from repeated sends.
	CreateKeyEnvelope(ctx context.Context, arg CreateKeyEnvelopeParams) (KeyEnvelope, error)
	// The author is both the creator and (so far) the last editor. created_by is set
	// ONLY here: no update path may rewrite it, so "«Home» · <owner nick>" keeps
	// naming who added the place, not whoever touched it last.
	CreatePlace(ctx context.Context, arg CreatePlaceParams) (PlacesEnc, error)
	CreateSOS(ctx context.Context, arg CreateSOSParams) (SosEvent, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateShareSession(ctx context.Context, arg CreateShareSessionParams) (ShareSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCircle(ctx context.Context, id uuid.UUID) error
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	// Delete pings older than each circle's retention window that still linger in
	// live partitions (belt-and-suspenders alongside partition drops).
	//
	// PruneStalePings above supersedes this for pings in the default config, but a
	// circle whose retention_days is shorter than PING_RETENTION_HOURS still wants
	// its pings gone sooner — whichever rule deletes more, deletes. The same
	// newest-per-device carve-out applies: an absolute rule, not a per-window one.
	DeleteExpiredPingsForCircle(ctx context.Context, arg DeleteExpiredPingsForCircleParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteMutes(ctx context.Context, arg DeleteMutesParams) error
	// Unsubscribe by the row's opaque address: a push endpoint URL for webpush, the
	// registration token for fcm. Both live in `endpoint`, so one query serves both.
	DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) error
	// Prune a subscription the push service reported as gone (404/410).
	DeletePushSubscriptionByID(ctx context.Context, id uuid.UUID) error
	EmailExists(ctx context.Context, email string) (bool, error)
	// --- retention / maintenance ---
	EnsurePingPartitions(ctx context.Context, arg EnsurePingPartitionsParams) error
	GetCircle(ctx context.Context, id uuid.UUID) (Circle, error)
	GetDevice(ctx context.Context, id uuid.UUID) (Device, error)
	GetDeviceForUser(ctx context.Context, arg GetDeviceForUserParams) (Device, error)
	GetInvite(ctx context.Context, id uuid.UUID) (Invite, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (CircleMember, error)
	GetSOS(ctx context.Context, id uuid.UUID) (SosEvent, error)
	// Resolve an access token to a live session (not revoked, not expired).
	GetSessionByAccessHash(ctx context.Context, accessTokenHash string) (Session, error)
	// Look up a session where the presented refresh matches the PREVIOUS hash:
	// a replay of an already-rotated token → theft signal.
	GetSessionByPrevRefreshHash(ctx context.Context, prevRefreshHash *string) (Session, error)
	// Look up a session by the current refresh hash (valid refresh).
	GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetSharePosition(ctx context.Context, sessionID uuid.UUID) (SharePosition, error)
	// Public lookup by id alone: the viewer is unregistered and holds only the link.
	GetShareSession(ctx context.Context, id uuid.UUID) (ShareSession, error)
	// Ownership-scoped lookup; no row means unknown-or-not-yours (both → 404, so a
	// stranger cannot probe for the existence of someone else's link).
	GetShareSessionForOwner(ctx context.Context, arg GetShareSessionForOwnerParams) (ShareSession, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Idempotent: the UNIQUE (user_id, circle_id, muted_user_id) NULLS NOT DISTINCT
	// constraint makes re-muting the same target — or the circle — a no-op.
	InsertMute(ctx context.Context, arg InsertMuteParams) error
	// Idempotent insert of one encrypted ping. Retries of the same
	// (device_id, client_id, captured_at) are dropped. Returns the row only when a
	// NEW ping was inserted, so the handler knows what to fan out over realtime.
	InsertPing(ctx context.Context, arg InsertPingParams) (Ping, error)
	// --- app versions ---
	LatestActiveVersion(ctx context.Context, platform string) (AppVersion, error)
	// Latest ping per device in a circle (for the live map).
	LatestPingsForCircle(ctx context.Context, circleID uuid.UUID) ([]Ping, error)
	ListActiveSOS(ctx context.Context, circleID uuid.UUID) ([]SosEvent, error)
	ListActiveSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsForUserRow, error)
	ListAuditForUser(ctx context.Context, arg ListAuditForUserParams) ([]AuditLog, error)
	// List devices of all members of a circle (recipients for key envelopes).
	ListCircleDevices(ctx context.Context, circleID uuid.UUID) ([]Device, error)
	// Every push subscription that should receive the sender's notification: the
	// circle's members, minus the sender themselves (who must not notify their own
	// devices), minus anyone who muted this circle or muted the sender. Drives the
	// /notify fan-out.
	//
	// The mute filter lives HERE, on the send path, because the product requirement
	// is "other members stop sending to me" — a muted recipient's endpoint is never
	// handed to the push service, rather than the device receiving the push and
	// hiding it. sender_user_id is therefore both the excluded user and the mute
	// target to test: they are the same person.
	//
	// `kind` selects the delivery channel per row (webpush or fcm); a member with
	// both a browser subscription and a phone token simply has two rows and gets
	// both. The mute filter below is channel-agnostic on purpose: it drops the
	// RECIPIENT, so muting silences every device they own, not just their browser.
	ListCirclePushSubscriptions(ctx context.Context, arg ListCirclePushSubscriptionsParams) ([]ListCirclePushSubscriptionsRow, error)
	ListCirclesForUser(ctx context.Context, userID uuid.UUID) ([]ListCirclesForUserRow, error)
	ListDevicesForUser(ctx context.Context, userID uuid.UUID) ([]Device, error)
	ListInvitesForCircle(ctx context.Context, circleID uuid.UUID) ([]Invite, error)
	ListMembers(ctx context.Context, circleID uuid.UUID) ([]ListMembersRow, error)
	// The caller's own mutes in one circle. A NULL muted_user_id row means the
	// whole circle is muted; every other row names one muted member.
	ListMutes(ctx context.Context, arg ListMutesParams) ([]*uuid.UUID, error)
	ListPlaces(ctx context.Context, circleID uuid.UUID) ([]PlacesEnc, error)
	// The caller's own live-or-revoked links that have not yet expired. Expired ones
	// are gone from the UI's point of view (and the retention job removes them).
	ListShareSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ShareSession, error)
	MarkEnvelopeConsumed(ctx context.Context, arg MarkEnvelopeConsumedParams) error
	// Pending (unconsumed) envelopes addressed to a device, bounded.
	PendingEnvelopesForDevice(ctx context.Context, recipientDeviceID uuid.UUID) ([]KeyEnvelope, error)
	PruneAuditIPs(ctx context.Context, keepDays int32) (int64, error)
	// Prune consumed envelopes and stale unconsumed ones (privacy + storage bound).
	PruneKeyEnvelopes(ctx context.Context) (int64, error)
	// NOTE: listing/dropping ping partitions queries pg_catalog (pg_inherits),
	// which sqlc's analyzer does not model; that runs as raw pgx in the retention
	// package (see internal/retention).
	PruneLoginAttempts(ctx context.Context, keepDays int32) (int64, error)
	// Hard-delete soft-deleted place tombstones once clients have had time to
	// converge the deletion (privacy + storage bound).
	PrunePlaceTombstones(ctx context.Context, updatedAt time.Time) (int64, error)
	// Prune resolved SOS events past the retention horizon (unbounded-growth bound).
	PruneResolvedSOS(ctx context.Context, resolvedAt *time.Time) (int64, error)
	// Drop dead share sessions (and, by cascade, their position) once the grace
	// period has passed, so the table cannot grow without bound.
	PruneShareSessions(ctx context.Context, graceHours int32) (int64, error)
	// Delete every ping older than the global ping window EXCEPT the newest one per
	// (circle_id, device_id), which is kept no matter how old it is.
	//
	// Why: since D-0054 removed history and the movement/digest stats, the only
	// reader left is "latest ping per device" (LatestPingsForCircle) plus the
	// realtime fan-out, which publishes on insert and never reads back. Stored
	// history is therefore unreadable-but-present ciphertext whose timing and
	// frequency still leak to whoever steals the database (THREAT_MODEL §4). The
	// short window is what dedup (uq_pings_dedup) and in-flight reads need; the
	// per-device carve-out is what the map needs — drop it and a phone that has
	// been off for three days silently blanks off everyone's map.
	//
	// "Not the newest" is expressed as "a newer ping exists for the same circle and
	// device", which idx_pings_circle_device_time (circle_id, device_id,
	// captured_at DESC) serves directly, and the outer captured_at bound lets the
	// planner prune whole monthly partitions. Ties at a device's max captured_at
	// (possible: dedup is keyed by client_id too) all survive, so whichever row
	// LatestPingsForCircle's DISTINCT ON picks is guaranteed to still be there.
	PruneStalePings(ctx context.Context, keepHours int32) (int64, error)
	// --- login attempts (persistent lockout) ---
	RecordLoginAttempt(ctx context.Context, arg RecordLoginAttemptParams) error
	RemoveMember(ctx context.Context, arg RemoveMemberParams) error
	ResolveSOS(ctx context.Context, arg ResolveSOSParams) (SosEvent, error)
	RevokeInvite(ctx context.Context, arg RevokeInviteParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionsForDevice(ctx context.Context, deviceID uuid.UUID) error
	RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) error
	// Idempotent revoke: COALESCE keeps the first revocation's timestamp, so calling
	// it twice still returns the row (200) rather than looking like a missing link.
	RevokeShareSession(ctx context.Context, arg RevokeShareSessionParams) (ShareSession, error)
	// Rotate: issue new access+refresh, keep the presented refresh as prev. This is
	// a compare-and-swap on the presented refresh hash so that two concurrent
	// refreshes of the same token cannot both succeed: only the request whose
	// old_refresh_hash still matches the current one rotates; the loser matches 0
	// rows and the caller treats it as reuse (see auth.Refresh).
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	SetDevicePubkey(ctx context.Context, arg SetDevicePubkeyParams) error
	SetDevicePushToken(ctx context.Context, arg SetDevicePushTokenParams) error
	SetMemberProfile(ctx context.Context, arg SetMemberProfileParams) error
	SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (CircleMember, error)
	SetPrecisionMode(ctx context.Context, arg SetPrecisionModeParams) (CircleMember, error)
	// Soft-delete only a live place. The `deleted = false` guard makes re-deleting a
	// tombstone a no-op (returns no row → 404) instead of refreshing updated_at
	// (which would defeat tombstone retention) or inflating the version.
	SoftDeletePlace(ctx context.Context, arg SoftDeletePlaceParams) (PlacesEnc, error)
	TouchDevice(ctx context.Context, id uuid.UUID) error
	UpdateCircleName(ctx context.Context, arg UpdateCircleNameParams) (Circle, error)
	UpdateCircleRetention(ctx context.Context, arg UpdateCircleRetentionParams) (Circle, error)
	// Optimistic-concurrency update: only if the caller's version matches.
	UpdatePlace(ctx context.Context, arg UpdatePlaceParams) (PlacesEnc, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertAppVersion(ctx context.Context, arg UpsertAppVersionParams) (AppVersion, error)
	// --- push subscriptions ---
	// Register a device for push on either channel. `kind` says how to read the
	// row: a webpush row's endpoint is a push-service URL with p256dh/auth beside
	// it; an fcm row's endpoint IS the registration token, with both keys NULL
	// (see migration 00008). One row shape, one unique key, one prune path.
	//
	// kind is updated on conflict too: the same opaque string re-registering under
	// the other channel is nonsense, but if it ever happened the row must not keep
	// claiming a shape its key material no longer matches.
	UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error)
	// Latest sealed position only: the new fix replaces the old one in place.
	UpsertSharePosition(ctx context.Context, arg UpsertSharePositionParams) error
	// --- audit log ---
	WriteAudit(ctx context.Context, arg WriteAuditParams) error
}

var _ Querier = (*Queries)(nil)
