// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, device_id, access_token_hash, refresh_token_hash,
    access_expires_at, refresh_expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, device_id, access_token_hash, refresh_token_hash, prev_refresh_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, rotated_at
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	DeviceID         uuid.UUID
	AccessTokenHash  string
	RefreshTokenHash string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.DeviceID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.PrevRefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE refresh_expires_at < now() - interval '1 day'
   OR (revoked_at IS NOT NULL AND revoked_at < now() - interval '1 day')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByAccessHash = `-- name: GetSessionByAccessHash :one
SELECT id, user_id, device_id, access_token_hash, refresh_token_hash, prev_refresh_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, rotated_at FROM sessions
WHERE access_token_hash = $1
  AND revoked_at IS NULL
  AND access_expires_at > now()
`

// Resolve an access token to a live session (not revoked, not expired).
func (q *Queries) GetSessionByAccessHash(ctx context.Context, accessTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByAccessHash, accessTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.PrevRefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getSessionByPrevRefreshHash = `-- name: GetSessionByPrevRefreshHash :one
SELECT id, user_id, device_id, access_token_hash, refresh_token_hash, prev_refresh_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, rotated_at FROM sessions
WHERE prev_refresh_hash = $1
  AND revoked_at IS NULL
`

// Look up a session where the presented refresh matches the PREVIOUS hash:
// a replay of an already-rotated token → theft signal.
func (q *Queries) GetSessionByPrevRefreshHash(ctx context.Context, prevRefreshHash *string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByPrevRefreshHash, prevRefreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.PrevRefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, device_id, access_token_hash, refresh_token_hash, prev_refresh_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, rotated_at FROM sessions
WHERE refresh_token_hash = $1
  AND revoked_at IS NULL
  AND refresh_expires_at > now()
`

// Look up a session by the current refresh hash (valid refresh).
func (q *Queries) GetSessionByRefreshHash(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.PrevRefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const listActiveSessionsForUser = `-- name: ListActiveSessionsForUser :many
SELECT s.id, s.user_id, s.device_id, s.access_token_hash, s.refresh_token_hash, s.prev_refresh_hash, s.access_expires_at, s.refresh_expires_at, s.revoked_at, s.created_at, s.rotated_at, d.platform, d.display_name
FROM sessions s
JOIN devices d ON d.id = s.device_id
WHERE s.user_id = $1 AND s.revoked_at IS NULL AND s.refresh_expires_at > now()
ORDER BY s.rotated_at DESC
`

type ListActiveSessionsForUserRow struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	DeviceID         uuid.UUID
	AccessTokenHash  string
	RefreshTokenHash string
	PrevRefreshHash  *string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
	RotatedAt        time.Time
	Platform         string
	DisplayName      *string
}

func (q *Queries) ListActiveSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ListActiveSessionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsForUserRow{}
	for rows.Next() {
		var i ListActiveSessionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceID,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.PrevRefreshHash,
			&i.AccessExpiresAt,
			&i.RefreshExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.Platform,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionsForDevice = `-- name: RevokeSessionsForDevice :exec
UPDATE sessions SET revoked_at = now()
WHERE device_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForDevice(ctx context.Context, deviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionsForDevice, deviceID)
	return err
}

const revokeSessionsForUser = `-- name: RevokeSessionsForUser :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionsForUser, userID)
	return err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions SET
    access_token_hash  = $2,
    refresh_token_hash = $3,
    prev_refresh_hash  = $6,
    access_expires_at  = $4,
    refresh_expires_at = $5,
    rotated_at = now()
WHERE id = $1
  AND refresh_token_hash = $6
  AND revoked_at IS NULL
RETURNING id, user_id, device_id, access_token_hash, refresh_token_hash, prev_refresh_hash, access_expires_at, refresh_expires_at, revoked_at, created_at, rotated_at
`

type RotateSessionParams struct {
	ID               uuid.UUID
	AccessTokenHash  string
	RefreshTokenHash string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	OldRefreshHash   *string
}

// Rotate: issue new access+refresh, keep the presented refresh as prev. This is
// a compare-and-swap on the presented refresh hash so that two concurrent
// refreshes of the same token cannot both succeed: only the request whose
// old_refresh_hash still matches the current one rotates; the loser matches 0
// rows and the caller treats it as reuse (see auth.Refresh).
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.ID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
		arg.OldRefreshHash,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.PrevRefreshHash,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}
