// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindShareViewer = `-- name: BindShareViewer :one
UPDATE share_sessions
SET viewer_token_hash = $2, viewer_bound_at = now()
WHERE id = $1 AND viewer_token_hash IS NULL
RETURNING id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at
`

type BindShareViewerParams struct {
	ID              uuid.UUID
	ViewerTokenHash []byte
}

// One-device binding, compare-and-swap: only the request that finds
// viewer_token_hash still NULL binds the link and gets the row back. A racing
// second viewer matches no row and is refused, so a link can never be bound
// twice.
func (q *Queries) BindShareViewer(ctx context.Context, arg BindShareViewerParams) (ShareSession, error) {
	row := q.db.QueryRow(ctx, bindShareViewer, arg.ID, arg.ViewerTokenHash)
	var i ShareSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewerTokenHash,
		&i.ViewerBoundAt,
	)
	return i, err
}

const createShareSession = `-- name: CreateShareSession :one
INSERT INTO share_sessions (user_id, expires_at)
VALUES ($1, $2)
RETURNING id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at
`

type CreateShareSessionParams struct {
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateShareSession(ctx context.Context, arg CreateShareSessionParams) (ShareSession, error) {
	row := q.db.QueryRow(ctx, createShareSession, arg.UserID, arg.ExpiresAt)
	var i ShareSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewerTokenHash,
		&i.ViewerBoundAt,
	)
	return i, err
}

const getSharePosition = `-- name: GetSharePosition :one
SELECT session_id, nonce, ciphertext, captured_at, updated_at FROM share_positions WHERE session_id = $1
`

func (q *Queries) GetSharePosition(ctx context.Context, sessionID uuid.UUID) (SharePosition, error) {
	row := q.db.QueryRow(ctx, getSharePosition, sessionID)
	var i SharePosition
	err := row.Scan(
		&i.SessionID,
		&i.Nonce,
		&i.Ciphertext,
		&i.CapturedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareSession = `-- name: GetShareSession :one
SELECT id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at FROM share_sessions WHERE id = $1
`

// Public lookup by id alone: the viewer is unregistered and holds only the link.
func (q *Queries) GetShareSession(ctx context.Context, id uuid.UUID) (ShareSession, error) {
	row := q.db.QueryRow(ctx, getShareSession, id)
	var i ShareSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewerTokenHash,
		&i.ViewerBoundAt,
	)
	return i, err
}

const getShareSessionForOwner = `-- name: GetShareSessionForOwner :one
SELECT id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at FROM share_sessions WHERE id = $1 AND user_id = $2
`

type GetShareSessionForOwnerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Ownership-scoped lookup; no row means unknown-or-not-yours (both → 404, so a
// stranger cannot probe for the existence of someone else's link).
func (q *Queries) GetShareSessionForOwner(ctx context.Context, arg GetShareSessionForOwnerParams) (ShareSession, error) {
	row := q.db.QueryRow(ctx, getShareSessionForOwner, arg.ID, arg.UserID)
	var i ShareSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewerTokenHash,
		&i.ViewerBoundAt,
	)
	return i, err
}

const listShareSessionsForUser = `-- name: ListShareSessionsForUser :many
SELECT id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at FROM share_sessions
WHERE user_id = $1 AND expires_at > now()
ORDER BY created_at DESC
`

// The caller's own live-or-revoked links that have not yet expired. Expired ones
// are gone from the UI's point of view (and the retention job removes them).
func (q *Queries) ListShareSessionsForUser(ctx context.Context, userID uuid.UUID) ([]ShareSession, error) {
	rows, err := q.db.Query(ctx, listShareSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShareSession{}
	for rows.Next() {
		var i ShareSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.ViewerTokenHash,
			&i.ViewerBoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneShareSessions = `-- name: PruneShareSessions :execrows
DELETE FROM share_sessions
WHERE expires_at < now() - make_interval(hours => $1::int)
   OR (revoked_at IS NOT NULL
       AND revoked_at < now() - make_interval(hours => $1::int))
`

// Drop dead share sessions (and, by cascade, their position) once the grace
// period has passed, so the table cannot grow without bound.
func (q *Queries) PruneShareSessions(ctx context.Context, graceHours int32) (int64, error) {
	result, err := q.db.Exec(ctx, pruneShareSessions, graceHours)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeShareSession = `-- name: RevokeShareSession :one
UPDATE share_sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, created_at, expires_at, revoked_at, viewer_token_hash, viewer_bound_at
`

type RevokeShareSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Idempotent revoke: COALESCE keeps the first revocation's timestamp, so calling
// it twice still returns the row (200) rather than looking like a missing link.
func (q *Queries) RevokeShareSession(ctx context.Context, arg RevokeShareSessionParams) (ShareSession, error) {
	row := q.db.QueryRow(ctx, revokeShareSession, arg.ID, arg.UserID)
	var i ShareSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ViewerTokenHash,
		&i.ViewerBoundAt,
	)
	return i, err
}

const upsertSharePosition = `-- name: UpsertSharePosition :exec
INSERT INTO share_positions (session_id, nonce, ciphertext, captured_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (session_id) DO UPDATE SET
    nonce = EXCLUDED.nonce,
    ciphertext = EXCLUDED.ciphertext,
    captured_at = EXCLUDED.captured_at,
    updated_at = now()
`

type UpsertSharePositionParams struct {
	SessionID  uuid.UUID
	Nonce      []byte
	Ciphertext []byte
	CapturedAt time.Time
}

// Latest sealed position only: the new fix replaces the old one in place.
func (q *Queries) UpsertSharePosition(ctx context.Context, arg UpsertSharePositionParams) error {
	_, err := q.db.Exec(ctx, upsertSharePosition,
		arg.SessionID,
		arg.Nonce,
		arg.Ciphertext,
		arg.CapturedAt,
	)
	return err
}
