// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sos.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSOS = `-- name: CreateSOS :one
INSERT INTO sos_events (circle_id, device_id, ciphertext)
VALUES ($1, $2, $3)
RETURNING id, circle_id, device_id, ciphertext, created_at, resolved_at, resolved_by
`

type CreateSOSParams struct {
	CircleID   uuid.UUID
	DeviceID   *uuid.UUID
	Ciphertext []byte
}

func (q *Queries) CreateSOS(ctx context.Context, arg CreateSOSParams) (SosEvent, error) {
	row := q.db.QueryRow(ctx, createSOS, arg.CircleID, arg.DeviceID, arg.Ciphertext)
	var i SosEvent
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.DeviceID,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getSOS = `-- name: GetSOS :one
SELECT id, circle_id, device_id, ciphertext, created_at, resolved_at, resolved_by FROM sos_events WHERE id = $1
`

func (q *Queries) GetSOS(ctx context.Context, id uuid.UUID) (SosEvent, error) {
	row := q.db.QueryRow(ctx, getSOS, id)
	var i SosEvent
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.DeviceID,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const listActiveSOS = `-- name: ListActiveSOS :many
SELECT id, circle_id, device_id, ciphertext, created_at, resolved_at, resolved_by FROM sos_events
WHERE circle_id = $1 AND resolved_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSOS(ctx context.Context, circleID uuid.UUID) ([]SosEvent, error) {
	rows, err := q.db.Query(ctx, listActiveSOS, circleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SosEvent{}
	for rows.Next() {
		var i SosEvent
		if err := rows.Scan(
			&i.ID,
			&i.CircleID,
			&i.DeviceID,
			&i.Ciphertext,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneResolvedSOS = `-- name: PruneResolvedSOS :execrows
DELETE FROM sos_events
WHERE resolved_at IS NOT NULL AND resolved_at < $1
`

// Prune resolved SOS events past the retention horizon (unbounded-growth bound).
func (q *Queries) PruneResolvedSOS(ctx context.Context, resolvedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneResolvedSOS, resolvedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveSOS = `-- name: ResolveSOS :one
UPDATE sos_events
SET resolved_at = now(), resolved_by = $3
WHERE id = $1 AND circle_id = $2 AND resolved_at IS NULL
RETURNING id, circle_id, device_id, ciphertext, created_at, resolved_at, resolved_by
`

type ResolveSOSParams struct {
	ID         uuid.UUID
	CircleID   uuid.UUID
	ResolvedBy *uuid.UUID
}

func (q *Queries) ResolveSOS(ctx context.Context, arg ResolveSOSParams) (SosEvent, error) {
	row := q.db.QueryRow(ctx, resolveSOS, arg.ID, arg.CircleID, arg.ResolvedBy)
	var i SosEvent
	err := row.Scan(
		&i.ID,
		&i.CircleID,
		&i.DeviceID,
		&i.Ciphertext,
		&i.CreatedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}
