import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:aul/src/crypto/safety_code.dart';
import 'package:flutter_test/flutter_test.dart';

Uint8List _fromHex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

void main() {
  group('SafetyCode cross-language vectors', () {
    // The canonical vectors are generated by the Go implementation
    // (server/internal/crypto). This test proves the Dart implementation
    // reproduces them byte-for-byte — the Dart⇄Go interop guarantee.
    final file = File('../vectors/crypto-vectors.json');

    test('reproduces every committed Go safety-code vector', () {
      expect(
        file.existsSync(),
        isTrue,
        reason: 'run `go test ./internal/crypto -run Vectors -update` first',
      );
      final data = json.decode(file.readAsStringSync()) as Map<String, dynamic>;
      final vectors = data['safety_code'] as List<dynamic>;
      expect(vectors, isNotEmpty);

      for (final v in vectors.cast<Map<String, dynamic>>()) {
        final pubA = _fromHex(v['pub_a_hex'] as String);
        final pubB = _fromHex(v['pub_b_hex'] as String);
        final code = SafetyCode.compute(pubA, pubB);

        expect(
          code.emojis,
          (v['emojis'] as List).cast<String>(),
          reason: 'emoji mismatch for ${v['pub_a_hex']}',
        );
        expect(
          code.hexFallback,
          v['hex_fallback'],
          reason: 'hex fallback mismatch',
        );
        expect(_hex(code.digest), v['digest_hex'], reason: 'digest mismatch');
      }
    });

    test('is order-independent', () {
      final a = Uint8List(32)..fillRange(0, 32, 0x11);
      final b = Uint8List(32)..fillRange(0, 32, 0xEE);
      expect(
        SafetyCode.compute(a, b).display,
        SafetyCode.compute(b, a).display,
      );
    });

    test('rejects wrong-length keys', () {
      expect(
        () => SafetyCode.compute(Uint8List(31), Uint8List(32)),
        throwsArgumentError,
      );
    });
  });
}

String _hex(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
