package crypto

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// updateVectors regenerates the committed cross-language vectors file:
//
//	go test ./internal/crypto -run Vectors -update
var updateVectors = flag.Bool("update", false, "regenerate /vectors/crypto-vectors.json")

// vectorsFile is the canonical cross-client crypto test-vector artifact. The
// Dart and JS clients load the same file and must reproduce every value. It is
// resolved relative to this source file so the test is cwd-independent.
func vectorsFile(t *testing.T) string {
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate source file")
	}
	// .../server/internal/crypto/vectors_test.go -> repo root is three up
	// (crypto -> internal -> server -> repo root).
	root := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	return filepath.Join(root, "vectors", "crypto-vectors.json")
}

type cryptoVectors struct {
	Comment    string            `json:"_comment"`
	SafetyCode []safetyVector    `json:"safety_code"`
	Scheme     safetyCodeMeta    `json:"safety_code_scheme"`
	Aead       []aeadVector      `json:"aead_xchacha20poly1305_ietf"`
	SealedBox  []sealedBoxVector `json:"crypto_box_seal"`
	Place      []placeVector     `json:"place_framed"`
}

// placeVector pins the exact byte layout Phase-5 places/SOS use: the plaintext is
// padded to a fixed block (libsodium sodium_pad) then sealed into a self-framed
// blob (nonce || ciphertext). Clients MUST reproduce padded_hex from pad() and
// recover plaintext_utf8 by opening framed_hex and unpadding — pinning padding +
// framing across Go/JS/Dart, not just per-language round-trips (D-0034).
type placeVector struct {
	KeyHex        string `json:"key_hex"`
	NonceHex      string `json:"nonce_hex"`
	PlaintextUTF8 string `json:"plaintext_utf8"`
	AdUTF8        string `json:"ad_utf8"` // domain-separation associated data
	Block         int    `json:"block"`
	PaddedHex     string `json:"padded_hex"`
	FramedHex     string `json:"framed_hex"`
}

// sodiumPad reproduces libsodium's sodium_pad (ISO/IEC 7816-4): append 0x80 then
// 0x00 up to the next multiple of blocksize (a full extra block when already
// aligned). Used only to generate the pinned place vector.
func sodiumPad(data []byte, blocksize int) []byte {
	xpadlen := blocksize - 1 - (len(data) % blocksize)
	out := make([]byte, len(data)+xpadlen+1)
	copy(out, data)
	out[len(data)] = 0x80
	return out
}

// sealedBoxVector pins crypto_box_seal interop (key-envelope path): clients must
// OPEN this sealed box with the recipient keypair and recover the plaintext.
type sealedBoxVector struct {
	RecipientPrivHex string `json:"recipient_priv_hex"`
	RecipientPubHex  string `json:"recipient_pub_hex"`
	PlaintextHex     string `json:"plaintext_hex"`
	SealedHex        string `json:"sealed_hex"`
}

// aeadVector pins XChaCha20-Poly1305-IETF interop: clients must decrypt these
// ciphertexts and reproduce them from the plaintext, key, and nonce.
type aeadVector struct {
	KeyHex        string `json:"key_hex"`
	NonceHex      string `json:"nonce_hex"`
	PlaintextUTF8 string `json:"plaintext_utf8"`
	AdHex         string `json:"ad_hex"`
	CiphertextHex string `json:"ciphertext_hex"`
}

type safetyCodeMeta struct {
	Domain       string     `json:"domain"`
	Hash         string     `json:"hash"`
	EmojiPerCode int        `json:"emoji_per_code"`
	Alphabet     [64]string `json:"alphabet"`
}

type safetyVector struct {
	PubAHex     string   `json:"pub_a_hex"`
	PubBHex     string   `json:"pub_b_hex"`
	DigestHex   string   `json:"digest_hex"`
	Emojis      []string `json:"emojis"`
	HexFallback string   `json:"hex_fallback"`
}

func buildVectors(t *testing.T) cryptoVectors {
	inputs := []struct{ a, b []byte }{
		{key(0x00), key(0xFF)},
		{key(0x01), key(0x02)},
		{mustHex(t, "e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c"),
			mustHex(t, "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")},
		{key(0xAA), key(0x55)},
	}
	v := cryptoVectors{
		Comment: "Canonical Aul crypto test vectors. Dart and JS clients MUST reproduce every value. " +
			"Generated by server/internal/crypto vectors_test.go; regenerate with `go test ./internal/crypto -run Vectors -update`.",
		Scheme: safetyCodeMeta{
			Domain:       safetyCodeDomain,
			Hash:         "SHA-256(domain || 0x00 || low || high); low,high = sorted(pubA,pubB); emoji_i = alphabet[digest_i % 64]",
			EmojiPerCode: SafetyCodeLength,
			Alphabet:     SafetyEmojiAlphabet,
		},
	}
	for _, in := range inputs {
		c, err := ComputeSafetyCode(in.a, in.b)
		if err != nil {
			t.Fatalf("compute vector: %v", err)
		}
		v.SafetyCode = append(v.SafetyCode, safetyVector{
			PubAHex:     hex.EncodeToString(in.a),
			PubBHex:     hex.EncodeToString(in.b),
			DigestHex:   hex.EncodeToString(c.Digest),
			Emojis:      c.Emojis,
			HexFallback: c.HexFallback(),
		})
	}

	// XChaCha20-Poly1305-IETF vectors.
	aeadInputs := []struct {
		key, nonce []byte
		plain, ad  string
	}{
		{key: fill(0x07, 32), nonce: fill(0x02, 24), plain: `{"lat":51.5074,"lng":-0.1278,"acc":8,"batt":93,"mode":"precise"}`, ad: ""},
		{key: fill(0xA5, 32), nonce: fill(0x5A, 24), plain: "aul ping payload — юникод ✓", ad: "circle-v1"},
		{key: mustHex(t, "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"),
			nonce: mustHex(t, "000102030405060708090a0b0c0d0e0f1011121314151617"), plain: "", ad: ""},
	}
	for _, in := range aeadInputs {
		ct, err := SealXChaCha20(in.key, in.nonce, []byte(in.plain), []byte(in.ad))
		if err != nil {
			t.Fatalf("seal vector: %v", err)
		}
		v.Aead = append(v.Aead, aeadVector{
			KeyHex:        hex.EncodeToString(in.key),
			NonceHex:      hex.EncodeToString(in.nonce),
			PlaintextUTF8: in.plain,
			AdHex:         hex.EncodeToString([]byte(in.ad)),
			CiphertextHex: hex.EncodeToString(ct),
		})
	}

	// crypto_box_seal vector. Sealed with a FIXED ephemeral seed so the output is
	// reproducible; the plaintext is a sample 32-byte circle key K_c.
	recipientPriv := mustHex(t, "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
	recipientPub, err := DeriveX25519Public(recipientPriv)
	if err != nil {
		t.Fatalf("derive pub: %v", err)
	}
	kcPlain := mustHex(t, "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
	sealed, err := SealAnonymousBox(kcPlain, recipientPub, bytes.NewReader(fill(0x42, 64)))
	if err != nil {
		t.Fatalf("seal box: %v", err)
	}
	v.SealedBox = append(v.SealedBox, sealedBoxVector{
		RecipientPrivHex: hex.EncodeToString(recipientPriv),
		RecipientPubHex:  hex.EncodeToString(recipientPub),
		PlaintextHex:     hex.EncodeToString(kcPlain),
		SealedHex:        hex.EncodeToString(sealed),
	})

	// place_framed vector: a terse place JSON padded to a 256-byte block, then
	// sealed as nonce||ciphertext under a fixed key+nonce (deterministic).
	placeKey := fill(0x11, 32)
	placeNonce := fill(0x22, 24)
	const placePlain = `{"n":"Home","lat":51.5074,"lng":-0.1278,"rad":150}`
	const placeAD = "aul-place:v1" // domain separation (must match clients)
	padded := sodiumPad([]byte(placePlain), 256)
	placeCT, err := SealXChaCha20(placeKey, placeNonce, padded, []byte(placeAD))
	if err != nil {
		t.Fatalf("seal place vector: %v", err)
	}
	framed := append(append([]byte{}, placeNonce...), placeCT...)
	v.Place = append(v.Place, placeVector{
		KeyHex:        hex.EncodeToString(placeKey),
		NonceHex:      hex.EncodeToString(placeNonce),
		PlaintextUTF8: placePlain,
		AdUTF8:        placeAD,
		Block:         256,
		PaddedHex:     hex.EncodeToString(padded),
		FramedHex:     hex.EncodeToString(framed),
	})
	return v
}

func fill(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}

func TestCryptoVectors(t *testing.T) {
	got := buildVectors(t)
	gotJSON, err := json.MarshalIndent(got, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	gotJSON = append(gotJSON, '\n')

	path := vectorsFile(t)
	if *updateVectors {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		if err := os.WriteFile(path, gotJSON, 0o644); err != nil {
			t.Fatalf("write vectors: %v", err)
		}
		t.Logf("wrote %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read vectors (run with -update to generate): %v", err)
	}
	if !bytes.Equal(bytes.TrimSpace(want), bytes.TrimSpace(gotJSON)) {
		t.Fatalf("committed vectors are stale; re-run: go test ./internal/crypto -run Vectors -update")
	}
}

func mustHex(t *testing.T, s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}
